---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi-minimal:latest

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  ansible_core:
    package_pip: ansible-core==2.13.*
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  system: bindep.txt

additional_build_steps:
  prepend_base:
    - RUN microdnf -y update && microdnf -y install python3 python3-pip git && microdnf clean all
  append_final:
    - RUN python3 --version
    - RUN ansible --version
    - RUN ansible-galaxy collection list
