---
- name: Baseline Linux via Role
  hosts: linux
  become: true
  gather_facts: true

  # vars:
  #   lab_timezone: "America/Sao_Paulo"
  #   lab_packages:
  #     - curl
  #     - vim
  #     - git

  # environment:
  #   ANSIBLE_ROLES_PATH: "{{ playbook_dir }}/../roles"

  roles:
    - baseline_linux
